import { supabase } from "@/lib/supabaseClient";
import { PHYSICIAN_SERVICES_TABLE } from "@/lib/physicianServices";

export const PHYSICIAN_FEE_SALES_TABLE = "physician_fee_sales" as const;
export const PHYSICIAN_FEE_SALE_ITEMS_TABLE = "physician_fee_sale_items" as const;
const USERS_TABLE = "users" as const;

/** Cashier marks the sale paid with this `physician_fee_sales.status`. */
export const PHYSICIAN_FEE_STATUS_PAID = "Paid" as const;

/** Human label for `physician_fee_sales.status` on open / not-yet-Paid rows (null → Open). */
export function formatPhysicianFeeSaleDisplayStatus(status: string | null | undefined): string {
  const s = (status ?? "").trim();
  if (!s) return "Open";
  return s;
}

export type PhysicianFeeSaleItemRow = {
  physician_service_id: number;
  quantity: number;
  unit_fee: number;
  discount: number;
  notes: string | null;
};

/** Replace all line items for a sale (delete then insert). `linenum` is 1-based row order; `total_fee` is generated by the DB. */
export async function replacePhysicianFeeSaleItems(
  physicianFeeSaleId: string,
  items: PhysicianFeeSaleItemRow[],
): Promise<{ error: string | null }> {
  const saleId = physicianFeeSaleId.trim();
  if (!saleId) return { error: "Missing sale id." };

  const { error: delErr } = await supabase
    .from(PHYSICIAN_FEE_SALE_ITEMS_TABLE)
    .delete()
    .eq("physician_fee_sale_id", saleId);
  if (delErr) return { error: delErr.message };

  if (items.length === 0) return { error: null };

  const rows = items.map((it, index) => ({
    physician_fee_sale_id: saleId,
    physician_service_id: it.physician_service_id,
    quantity: it.quantity,
    unit_fee: it.unit_fee,
    discount: it.discount,
    notes: it.notes,
    linenum: index + 1,
  }));

  const { error: insErr } = await supabase.from(PHYSICIAN_FEE_SALE_ITEMS_TABLE).insert(rows);
  return { error: insErr?.message ?? null };
}

export type PhysicianFeeSaleRow = {
  id: string;
  patient_id: number | null;
  encounter_id: string | null;
  physician_id: number | null;
  subtotal: number | string;
  discount_type_id: number | null;
  discount_amount: number | string;
  total_amount: number | string;
  notes: string | null;
  created_at: string;
  status?: string | null;
};

export type PhysicianFeeSaleWithStatus = PhysicianFeeSaleRow & { status: string | null };

export type PhysicianFeeSaleItemDetail = {
  id: string;
  physician_fee_sale_id: string;
  linenum: number;
  physician_service_id: number;
  quantity: number;
  unit_fee: number | string;
  discount: number | string;
  total_fee: number | string | null;
  notes: string | null;
  service_name: string | null;
};

/** Sales for an encounter that are not marked Paid at cashier. */
export async function fetchUnpaidPhysicianFeeSalesForEncounter(encounterId: string): Promise<{
  sales: PhysicianFeeSaleWithStatus[];
  error: string | null;
}> {
  const id = encounterId.trim();
  if (!id) return { sales: [], error: null };

  const res = await supabase
    .from(PHYSICIAN_FEE_SALES_TABLE)
    .select(
      "id, patient_id, encounter_id, physician_id, subtotal, discount_type_id, discount_amount, total_amount, notes, created_at, status",
    )
    .eq("encounter_id", id)
    .or(`status.is.null,status.neq.${PHYSICIAN_FEE_STATUS_PAID}`)
    .order("created_at", { ascending: false });

  if (res.error) return { sales: [], error: res.error.message };
  const rows = (res.data ?? []) as PhysicianFeeSaleWithStatus[];
  return { sales: rows, error: null };
}

/** Line items for one or more physician fee sales, with `physician_services.name`. */
export async function fetchPhysicianFeeSaleItemsWithServiceNames(saleIds: string[]): Promise<{
  itemsBySaleId: Map<string, PhysicianFeeSaleItemDetail[]>;
  error: string | null;
}> {
  const ids = [...new Set(saleIds.map((x) => String(x).trim()).filter(Boolean))];
  if (ids.length === 0) return { itemsBySaleId: new Map(), error: null };

  const { data, error } = await supabase
    .from(PHYSICIAN_FEE_SALE_ITEMS_TABLE)
    .select(
      "id, physician_fee_sale_id, linenum, physician_service_id, quantity, unit_fee, discount, total_fee, notes",
    )
    .in("physician_fee_sale_id", ids);

  if (error) return { itemsBySaleId: new Map(), error: error.message };

  type Raw = {
    id: string;
    physician_fee_sale_id: string;
    linenum: number;
    physician_service_id: number;
    quantity: number;
    unit_fee: number | string;
    discount: number | string;
    total_fee: number | string | null;
    notes: string | null;
  };

  const rawRows = (data ?? []) as Raw[];
  const svcIds = [...new Set(rawRows.map((r) => r.physician_service_id).filter((n) => Number.isFinite(n)))];
  const nameByServiceId = new Map<number, string>();

  if (svcIds.length > 0) {
    const svcRes = await supabase.from(PHYSICIAN_SERVICES_TABLE).select("id, name").in("id", svcIds);
    if (svcRes.error) return { itemsBySaleId: new Map(), error: svcRes.error.message };
    for (const row of (svcRes.data ?? []) as Array<{ id: number; name: string }>) {
      nameByServiceId.set(row.id, row.name ?? "");
    }
  }

  const itemsBySaleId = new Map<string, PhysicianFeeSaleItemDetail[]>();
  for (const r of rawRows) {
    const detail: PhysicianFeeSaleItemDetail = {
      id: r.id,
      physician_fee_sale_id: r.physician_fee_sale_id,
      linenum: r.linenum,
      physician_service_id: r.physician_service_id,
      quantity: r.quantity,
      unit_fee: r.unit_fee,
      discount: r.discount,
      total_fee: r.total_fee,
      notes: r.notes,
      service_name: nameByServiceId.get(r.physician_service_id) ?? null,
    };
    const list = itemsBySaleId.get(r.physician_fee_sale_id) ?? [];
    list.push(detail);
    itemsBySaleId.set(r.physician_fee_sale_id, list);
  }

  for (const [, list] of itemsBySaleId) {
    list.sort((a, b) => a.linenum - b.linenum);
  }

  for (const id of ids) {
    if (!itemsBySaleId.has(id)) itemsBySaleId.set(id, []);
  }

  return { itemsBySaleId, error: null };
}

function moneyNum(v: unknown): number {
  if (v == null) return 0;
  const n = typeof v === "number" ? v : Number(String(v));
  return Number.isFinite(n) ? n : 0;
}

export function physicianChargeLineKey(serviceId: string | number, unitFee: string | number): string {
  const sid = Number(String(serviceId).trim());
  const fee = moneyNum(unitFee);
  if (!Number.isFinite(sid) || sid <= 0) return "";
  return `${sid}|${fee}`;
}

export type PaidPhysicianLineStatus = {
  exactKeys: Set<string>;
  /** Paid unit fees per physician service id (string). */
  feesByServiceId: Map<string, Set<number>>;
};

export function isPhysicianChargeLinePaid(
  line: { serviceId: string; price: string },
  paid: PaidPhysicianLineStatus,
): boolean {
  const sid = line.serviceId.trim();
  if (!sid) return false;
  const fee = moneyNum(line.price);
  const key = physicianChargeLineKey(sid, fee);
  if (paid.exactKeys.has(key)) return true;
  const paidFees = paid.feesByServiceId.get(sid);
  if (!paidFees) return false;
  for (const pf of paidFees) {
    if (Math.abs(pf - fee) < 0.02) return true;
  }
  return false;
}

function isPaidPhysicianSaleStatus(status: string | null | undefined): boolean {
  return String(status ?? "").trim().toLowerCase() === PHYSICIAN_FEE_STATUS_PAID.toLowerCase();
}

function addPaidLineFromServiceAndFee(
  status: PaidPhysicianLineStatus,
  serviceId: string | number,
  unitFee: string | number,
): void {
  const sid = String(serviceId).trim();
  const fee = moneyNum(unitFee);
  if (!sid || !Number.isFinite(fee)) return;
  const key = physicianChargeLineKey(sid, fee);
  if (key) status.exactKeys.add(key);
  const set = status.feesByServiceId.get(sid) ?? new Set<number>();
  set.add(fee);
  status.feesByServiceId.set(sid, set);
}

/** Service lines already marked Paid at cashier for this visit (from all paid physician fee sales). */
export async function fetchPaidPhysicianLineStatusForEncounter(encounterId: string): Promise<{
  status: PaidPhysicianLineStatus;
  error: string | null;
}> {
  const empty: PaidPhysicianLineStatus = { exactKeys: new Set(), feesByServiceId: new Map() };
  const id = encounterId.trim();
  if (!id) return { status: empty, error: null };

  const res = await supabase
    .from(PHYSICIAN_FEE_SALES_TABLE)
    .select("id, status, notes")
    .eq("encounter_id", id);

  if (res.error) return { status: empty, error: res.error.message };

  const paidSales = ((res.data ?? []) as Array<{ id: string; status?: string | null; notes?: string | null }>).filter(
    (r) => isPaidPhysicianSaleStatus(r.status),
  );
  if (paidSales.length === 0) return { status: empty, error: null };

  const saleIds = paidSales.map((r) => r.id).filter(Boolean);
  const status: PaidPhysicianLineStatus = { exactKeys: new Set(), feesByServiceId: new Map() };

  for (const sale of paidSales) {
    if (!sale.notes) continue;
    try {
      const parsed = JSON.parse(sale.notes) as {
        charges_services_lines?: Array<{ serviceId?: string; price?: string }>;
      };
      for (const row of parsed.charges_services_lines ?? []) {
        addPaidLineFromServiceAndFee(status, row.serviceId ?? "", row.price ?? "");
      }
    } catch {
      // ignore invalid notes JSON
    }
  }

  const itemsRes = await fetchPhysicianFeeSaleItemsWithServiceNames(saleIds);
  if (itemsRes.error) return { status, error: itemsRes.error };

  for (const lines of itemsRes.itemsBySaleId.values()) {
    for (const line of lines) {
      addPaidLineFromServiceAndFee(status, line.physician_service_id, line.unit_fee);
    }
  }

  return { status, error: null };
}

/** @deprecated Use {@link fetchPaidPhysicianLineStatusForEncounter}. */
export async function fetchPaidPhysicianChargeLineKeysForEncounter(encounterId: string): Promise<{
  keys: Set<string>;
  error: string | null;
}> {
  const { status, error } = await fetchPaidPhysicianLineStatusForEncounter(encounterId);
  return { keys: status.exactKeys, error };
}

export async function fetchLatestPhysicianFeeSaleForEncounter(encounterId: string): Promise<{
  sale: PhysicianFeeSaleRow | null;
  error: string | null;
}> {
  const res = await supabase
    .from(PHYSICIAN_FEE_SALES_TABLE)
    .select(
      "id, patient_id, encounter_id, physician_id, subtotal, discount_type_id, discount_amount, total_amount, notes, created_at, status",
    )
    .eq("encounter_id", encounterId)
    .order("created_at", { ascending: false })
    .limit(1);

  if (res.error) return { sale: null, error: res.error.message };
  const rows = (res.data ?? []) as PhysicianFeeSaleRow[];
  return { sale: rows[0] ?? null, error: null };
}

export async function upsertPhysicianFeeSaleForEncounter(args: {
  existingId?: string | null;
  patientId: number | null;
  encounterId: string;
  physicianId: number | null;
  subtotal: number;
  discountAmount: number;
  totalAmount: number;
  discountTypeId: number | null;
  notes: string | null;
  servedBy?: string | null;
  /** When updating a sale already marked Paid at cashier, keep it Paid. */
  preservePaidStatus?: boolean;
}): Promise<{ id: string | null; error: string | null }> {
  let status: string = "Completed";
  if (args.existingId && args.preservePaidStatus) {
    const cur = await supabase
      .from(PHYSICIAN_FEE_SALES_TABLE)
      .select("status")
      .eq("id", args.existingId)
      .limit(1)
      .maybeSingle();
    if (!cur.error) {
      const s = String((cur.data as { status?: string | null } | null)?.status ?? "").trim();
      if (s === PHYSICIAN_FEE_STATUS_PAID) status = PHYSICIAN_FEE_STATUS_PAID;
    }
  }

  const payload = {
    patient_id: args.patientId,
    encounter_id: args.encounterId,
    physician_id: args.physicianId,
    subtotal: args.subtotal,
    discount_type_id: args.discountTypeId,
    discount_amount: args.discountAmount,
    vat_amount: 0,
    total_amount: args.totalAmount,
    status,
    served_by: args.servedBy ?? null,
    notes: args.notes,
  } as const;

  if (args.existingId) {
    const res = await supabase
      .from(PHYSICIAN_FEE_SALES_TABLE)
      .update(payload)
      .eq("id", args.existingId)
      .select("id")
      .limit(1);
    if (res.error) return { id: null, error: res.error.message };
    const id = (res.data as Array<{ id: string }> | null)?.[0]?.id ?? args.existingId;
    return { id, error: null };
  }

  const res = await supabase.from(PHYSICIAN_FEE_SALES_TABLE).insert(payload).select("id").limit(1);
  if (res.error) return { id: null, error: res.error.message };
  const id = (res.data as Array<{ id: string }> | null)?.[0]?.id ?? null;
  return { id, error: null };
}

export async function resolveValidPhysicianId(candidate: number | null): Promise<{
  physicianId: number | null;
  error: string | null;
}> {
  if (candidate == null) return { physicianId: null, error: null };
  const res = await supabase.from(USERS_TABLE).select("user_id").eq("user_id", candidate).limit(1);
  if (res.error) return { physicianId: null, error: res.error.message };
  const rows = (res.data ?? []) as Array<{ user_id: number }>;
  return { physicianId: rows.length > 0 ? candidate : null, error: null };
}

