import { supabase } from "@/lib/supabaseClient";
import { PHYSICIAN_SERVICES_TABLE } from "@/lib/physicianServices";

export const PHYSICIAN_FEE_SALES_TABLE = "physician_fee_sales" as const;
export const PHYSICIAN_FEE_SALE_ITEMS_TABLE = "physician_fee_sale_items" as const;
const USERS_TABLE = "users" as const;

/** Cashier marks the sale paid with this `physician_fee_sales.status`. */
export const PHYSICIAN_FEE_STATUS_PAID = "Paid" as const;

/** Human label for `physician_fee_sales.status` on open / not-yet-Paid rows (null → Open). */
export function formatPhysicianFeeSaleDisplayStatus(status: string | null | undefined): string {
  const s = (status ?? "").trim();
  if (!s) return "Open";
  return s;
}

export type PhysicianFeeSaleItemRow = {
  physician_service_id: number;
  quantity: number;
  unit_fee: number;
  discount: number;
  notes: string | null;
};

/** Replace all line items for a sale (delete then insert). `linenum` is 1-based row order; `total_fee` is generated by the DB. */
export async function replacePhysicianFeeSaleItems(
  physicianFeeSaleId: string,
  items: PhysicianFeeSaleItemRow[],
): Promise<{ error: string | null }> {
  const saleId = physicianFeeSaleId.trim();
  if (!saleId) return { error: "Missing sale id." };

  const { error: delErr } = await supabase
    .from(PHYSICIAN_FEE_SALE_ITEMS_TABLE)
    .delete()
    .eq("physician_fee_sale_id", saleId);
  if (delErr) return { error: delErr.message };

  if (items.length === 0) return { error: null };

  const rows = items.map((it, index) => ({
    physician_fee_sale_id: saleId,
    physician_service_id: it.physician_service_id,
    quantity: it.quantity,
    unit_fee: it.unit_fee,
    discount: it.discount,
    notes: it.notes,
    linenum: index + 1,
  }));

  const { error: insErr } = await supabase.from(PHYSICIAN_FEE_SALE_ITEMS_TABLE).insert(rows);
  return { error: insErr?.message ?? null };
}

export type PhysicianFeeSaleRow = {
  id: string;
  patient_id: number | null;
  encounter_id: string | null;
  physician_id: number | null;
  subtotal: number | string;
  discount_type_id: number | null;
  discount_amount: number | string;
  total_amount: number | string;
  notes: string | null;
  created_at: string;
  status?: string | null;
};

export type PhysicianFeeSaleWithStatus = PhysicianFeeSaleRow & { status: string | null };

export type PhysicianFeeSaleItemDetail = {
  id: string;
  physician_fee_sale_id: string;
  linenum: number;
  physician_service_id: number;
  quantity: number;
  unit_fee: number | string;
  discount: number | string;
  total_fee: number | string | null;
  notes: string | null;
  service_name: string | null;
};

/** Sales for an encounter that are not marked Paid at cashier. */
export async function fetchUnpaidPhysicianFeeSalesForEncounter(encounterId: string): Promise<{
  sales: PhysicianFeeSaleWithStatus[];
  error: string | null;
}> {
  const id = encounterId.trim();
  if (!id) return { sales: [], error: null };

  const res = await supabase
    .from(PHYSICIAN_FEE_SALES_TABLE)
    .select(
      "id, patient_id, encounter_id, physician_id, subtotal, discount_type_id, discount_amount, total_amount, notes, created_at, status",
    )
    .eq("encounter_id", id)
    .or(`status.is.null,status.neq.${PHYSICIAN_FEE_STATUS_PAID}`)
    .order("created_at", { ascending: false });

  if (res.error) return { sales: [], error: res.error.message };
  const rows = (res.data ?? []) as PhysicianFeeSaleWithStatus[];
  return { sales: rows, error: null };
}

/** Line items for one or more physician fee sales, with `physician_services.name`. */
export async function fetchPhysicianFeeSaleItemsWithServiceNames(saleIds: string[]): Promise<{
  itemsBySaleId: Map<string, PhysicianFeeSaleItemDetail[]>;
  error: string | null;
}> {
  const ids = [...new Set(saleIds.map((x) => String(x).trim()).filter(Boolean))];
  if (ids.length === 0) return { itemsBySaleId: new Map(), error: null };

  const { data, error } = await supabase
    .from(PHYSICIAN_FEE_SALE_ITEMS_TABLE)
    .select(
      "id, physician_fee_sale_id, linenum, physician_service_id, quantity, unit_fee, discount, total_fee, notes",
    )
    .in("physician_fee_sale_id", ids);

  if (error) return { itemsBySaleId: new Map(), error: error.message };

  type Raw = {
    id: string;
    physician_fee_sale_id: string;
    linenum: number;
    physician_service_id: number;
    quantity: number;
    unit_fee: number | string;
    discount: number | string;
    total_fee: number | string | null;
    notes: string | null;
  };

  const rawRows = (data ?? []) as Raw[];
  const svcIds = [...new Set(rawRows.map((r) => r.physician_service_id).filter((n) => Number.isFinite(n)))];
  const nameByServiceId = new Map<number, string>();

  if (svcIds.length > 0) {
    const svcRes = await supabase.from(PHYSICIAN_SERVICES_TABLE).select("id, name").in("id", svcIds);
    if (svcRes.error) return { itemsBySaleId: new Map(), error: svcRes.error.message };
    for (const row of (svcRes.data ?? []) as Array<{ id: number; name: string }>) {
      nameByServiceId.set(row.id, row.name ?? "");
    }
  }

  const itemsBySaleId = new Map<string, PhysicianFeeSaleItemDetail[]>();
  for (const r of rawRows) {
    const detail: PhysicianFeeSaleItemDetail = {
      id: r.id,
      physician_fee_sale_id: r.physician_fee_sale_id,
      linenum: r.linenum,
      physician_service_id: r.physician_service_id,
      quantity: r.quantity,
      unit_fee: r.unit_fee,
      discount: r.discount,
      total_fee: r.total_fee,
      notes: r.notes,
      service_name: nameByServiceId.get(r.physician_service_id) ?? null,
    };
    const list = itemsBySaleId.get(r.physician_fee_sale_id) ?? [];
    list.push(detail);
    itemsBySaleId.set(r.physician_fee_sale_id, list);
  }

  for (const [, list] of itemsBySaleId) {
    list.sort((a, b) => a.linenum - b.linenum);
  }

  for (const id of ids) {
    if (!itemsBySaleId.has(id)) itemsBySaleId.set(id, []);
  }

  return { itemsBySaleId, error: null };
}

export async function fetchLatestPhysicianFeeSaleForEncounter(encounterId: string): Promise<{
  sale: PhysicianFeeSaleRow | null;
  error: string | null;
}> {
  const res = await supabase
    .from(PHYSICIAN_FEE_SALES_TABLE)
    .select(
      "id, patient_id, encounter_id, physician_id, subtotal, discount_type_id, discount_amount, total_amount, notes, created_at",
    )
    .eq("encounter_id", encounterId)
    .order("created_at", { ascending: false })
    .limit(1);

  if (res.error) return { sale: null, error: res.error.message };
  const rows = (res.data ?? []) as PhysicianFeeSaleRow[];
  return { sale: rows[0] ?? null, error: null };
}

export async function upsertPhysicianFeeSaleForEncounter(args: {
  existingId?: string | null;
  patientId: number | null;
  encounterId: string;
  physicianId: number | null;
  subtotal: number;
  discountAmount: number;
  totalAmount: number;
  discountTypeId: number | null;
  notes: string | null;
  servedBy?: string | null;
}): Promise<{ id: string | null; error: string | null }> {
  const payload = {
    patient_id: args.patientId,
    encounter_id: args.encounterId,
    physician_id: args.physicianId,
    subtotal: args.subtotal,
    discount_type_id: args.discountTypeId,
    discount_amount: args.discountAmount,
    vat_amount: 0,
    total_amount: args.totalAmount,
    status: "Completed",
    served_by: args.servedBy ?? null,
    notes: args.notes,
  } as const;

  if (args.existingId) {
    const res = await supabase
      .from(PHYSICIAN_FEE_SALES_TABLE)
      .update(payload)
      .eq("id", args.existingId)
      .select("id")
      .limit(1);
    if (res.error) return { id: null, error: res.error.message };
    const id = (res.data as Array<{ id: string }> | null)?.[0]?.id ?? args.existingId;
    return { id, error: null };
  }

  const res = await supabase.from(PHYSICIAN_FEE_SALES_TABLE).insert(payload).select("id").limit(1);
  if (res.error) return { id: null, error: res.error.message };
  const id = (res.data as Array<{ id: string }> | null)?.[0]?.id ?? null;
  return { id, error: null };
}

export async function resolveValidPhysicianId(candidate: number | null): Promise<{
  physicianId: number | null;
  error: string | null;
}> {
  if (candidate == null) return { physicianId: null, error: null };
  const res = await supabase.from(USERS_TABLE).select("user_id").eq("user_id", candidate).limit(1);
  if (res.error) return { physicianId: null, error: res.error.message };
  const rows = (res.data ?? []) as Array<{ user_id: number }>;
  return { physicianId: rows.length > 0 ? candidate : null, error: null };
}

